### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by CosminGGeorgescu** [ClaudiuLBS/project.net#1]
https://github.com/ClaudiuLBS/project.net/blob/f97f56a3cf9afe52e7d1400f124bfd2bea0f6667/project.net/Controllers/BookmarksController.cs#L121

Think this should be "Cream"

**Comment by ClaudiuLBS** [comment]
@TanaseVictorFlavian ce parere ai?

**Comment by TanaseVictorFlavian** [comment]
@ClaudiuLBS are dreptate esti nebun

**Comment by ClaudiuLBS** [comment]
Ma simt nevoit sa apelez la inspectia tehnica pentru a initia niste verificari mai ample asupra subiectului

**Comment by CosminGGeorgescu** [comment]
@ClaudiuLBS any updates ? Putem sa inchidem issue-ul asta ?

**Comment by ClaudiuLBS** [comment]
@CosminGGeorgescu pana duminica se rezolva, putem sa-l bagam la sertar
